# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OC单例' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OC单例

end

target '封装_AFN框架' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking'
  # Pods for 封装_AFN框架

end

target '封装_AFN框架_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking'
  # Pods for 封装_AFN框架_swift

end
